/**
 * Hook-shim source generation.
 *
 * `remembug init` calls these to write the shim scripts under
 * `~/.remembug/hooks/`. We generate them rather than ship them as static
 * files in `dist` because npm's `files` glob does not follow `..` paths
 * — so the repo's top-level `hooks/` directory would not survive an
 * `npm install -g @devzen/remembug-cli` regardless of how it's referenced.
 *
 * The shim contents mirror the dev-time files at `<repo>/hooks/*.mjs`;
 * keep both in sync.
 */
const SHARED_SHIM = `import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const DEFAULT_PORT = 7842;

export function readConfigSync() {
  const home = process.env.REMEMBUG_HOME ?? join(homedir(), '.remembug');
  const cfgPath = join(home, 'config.json');
  if (!existsSync(cfgPath)) return { daemon: { port: DEFAULT_PORT } };
  try {
    return JSON.parse(readFileSync(cfgPath, 'utf8'));
  } catch {
    return { daemon: { port: DEFAULT_PORT } };
  }
}
`;

function eventShim(routePath: string, header: string): string {
  return `#!/usr/bin/env node
/**
 * ${header}
 *
 * Reads the JSON payload Claude Code sends on stdin and POSTs it to
 * the local Remembug daemon. Cheap and never blocks Claude — any failure
 * is silently swallowed.
 *
 * Generated by \`remembug init\`. Regenerate by re-running it.
 */
import { readConfigSync } from './_shared.mjs';

const port = readConfigSync().daemon.port;
const url = \`http://127.0.0.1:\${port}${routePath}\`;

let body = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  body += chunk;
});
process.stdin.on('end', async () => {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 1500);
    await fetch(url, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body,
      signal: controller.signal,
    }).catch(() => undefined);
    clearTimeout(timeout);
  } catch {
    // Hooks must never crash Claude.
  }
  process.exit(0);
});
`;
}

export interface HookShim {
  filename: string;
  contents: string;
}

export function hookShims(): HookShim[] {
  return [
    { filename: '_shared.mjs', contents: SHARED_SHIM },
    {
      filename: 'post-tool-use.mjs',
      contents: eventShim('/hook/post-tool-use', 'Remembug hook shim: PostToolUse.'),
    },
    {
      filename: 'stop.mjs',
      contents: eventShim('/hook/stop', 'Remembug hook shim: Stop.'),
    },
  ];
}
